config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :departments
  root to: 'products#index'
  get 'products/search', to: 'products#search', as: :search_product
  resources :products, only: %i[index new create edit update destroy]
  # get "products", to: "products#index"
  # get "products/new", to: "products#new"
  # post "products", to: "products#create"
  # get "products/:id/edit", to: "products#edit"
  # delete "products/:id/delete", to: "products#destroy", as: :product
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/department.rb
# frozen_string_literal: true

# `@name`
class Department < ApplicationRecord
end

app/models/product.rb
# frozen_string_literal: true

# `@name[min: 2]`
# `@description`
# `@department[belongs_to_optional, presence: true]`
# `@price[presence: true]`
# `@stock`
class Product < ApplicationRecord
  belongs_to :department, optional: true
  validates :name, length: { minimum: 2 }
  validates :price, :department, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
# frozen_string_literal: true

# -
class DepartmentsController < ApplicationController
  before_action :set_department, only: %i[show edit update destroy]

  # GET /departments or /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1 or /departments/1.json
  def show
    # @products_by_dep = Product.where(department: @department)
    @products_by_dep = Product.where("department_id = ?", @department.id)
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  # def edit
  # end

  # POST /departments or /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html do
          redirect_to departments_url,
                      notice: "Department was successfully created."
        end
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json do
          render json: @department.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /departments/1 or /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html do
          redirect_to departments_url,
                      notice: "#{@department.name} was successfully updated."
        end
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json do
          render json: @department.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /departments/1 or /departments/1.json
  def destroy
    if Product.any? { |prod| prod.department_id.to_s == params[:id] }
      msg = "Cannot delete #{@department.name} because it has Products."
    else
      @department.destroy
      msg = "#{@department.name} was successfully deleted."
    end
    respond_to do |format|
      format.html { redirect_to departments_url, notice: msg }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_department
    @department = Department.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def department_params
    params.require(:department).permit(:name)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

# Products Controller
class ProductsController < ApplicationController
  before_action :set_product, only: %i[edit update destroy]

  private

  def product_params
    params.require(:product).permit(
      :name,
      :description,
      :department_id,
      :price,
      :stock
    )
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def _render(view)
    @department = Department.all
    render view
  end

  public

  def index
    @products = Product.order(name: :asc)
    @on_sale = Product.order(:price).limit(1)
    @products_not_on_sale = @products.select { |prod| @on_sale.exclude? prod }
  end

  def new
    @department = Department.all
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = 'Poduct saved successfully.'
      redirect_to root_path
    else
      _render :new
    end
  end

  def edit
    _render :edit
  end

  def update
    if @product.update(product_params)
      flash[:notice] = 'Product updated successfully.'
      redirect_to root_path
    else
      _render :edit
    end
  end

  def destroy
    Product.destroy(params[:id])
    redirect_to root_path
  end

  def search
    @name = params[:name]
    @search = Product.where 'name like ?', "%#{@name}%"
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/departments_helper.rb
# frozen_string_literal: true

module DepartmentsHelper
end

app/helpers/products_helper.rb
# frozen_string_literal: true

module ProductsHelper
end

app/views/departments/_department.html.erb
<div id="<%= dom_id department %>">
  <p>
    <strong>Name:</strong>
    <%= department.name %>
  </p>

</div>

app/views/departments/_form.html.erb
<%= form_with(model: department) do |form| %>
  <% if department.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
        <% department.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class = "row">
    <div class = "col-sm-8">
      <div class = "form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
    </div>
  </div>

  <div>
    <%= form.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/departments/edit.html.erb
<h1>Editing department</h1>

<%= render "form", department: @department %>

<br>

<div>
  <%= link_to "Show Products", @department, class: "btn btn-default" %>
  <%= link_to "Back", departments_path, class: "btn btn-default" %>
</div>

app/views/departments/index.html.erb
<% if flash[:notice] %>
  <div class = "alert alert-info" role = "alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<h1>Departments</h1>

<table class = "table table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan = "3"></th>
    <tr>
  </thead>
  
  <tbody id="departments">
    <% @departments.each do |department| %>
      <%# <%= render department %>
      <tr>
        <td style = "width: 60%" ><%= department.name %></td>
        <td><%= link_to "Show", department, class: "btn btn-primary" %></td>
        <td><%= link_to "Edit", edit_department_path(department.id), class: "btn btn-primary" %></td>
        <td><%= button_to "Delete", department, method: :delete, class: "btn btn-danger",
        data: {confirm: "Are you sure you want to remove #{department.name}"} %></td>
      </tr>
    <% end %>
  </div>
</table>

<%= link_to "New Department", new_department_path, class: "btn btn-default" %>

app/views/departments/new.html.erb
<% @department.errors.full_messages.each do |msg| %>
  <div class = "alert alert-danger" role = "alert">
    <%= msg %>
  </div>
<% end %>

<h1>New department</h1>

<%= form_for @department do |form| %>
  <div class = "row">
    <div class = "col-sm-8">
      <div class = "form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
    </div>
  </div>

  <%= form.submit "Submit", class: "btn btn-primary" %>
<% end %>


<br>

<div>
  <%= link_to "Back to Departments", departments_path %>
</div>

app/views/departments/show.html.erb
<% if flash[:notice] %>
  <div class = "alert alert-success" role = "alert">
    <%= flash[:notice] %>
  </div>
<% end %>
<table class="table table-bordered table-hover">
  <%= render :partial => "products/product_head" %>
  <%= render @products_by_dep %>
</table>

<div>
  <%= link_to "Edit Department", edit_department_path(@department), class: "btn btn-default" %>
  <%= link_to "Back", departments_path, class: "btn btn-default" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoR Store</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= nav_bar brand: "RoR Store", brand_link: root_url do %>
      <%= menu_group do %>
        <%= menu_item "Products", products_path %>
        <%= menu_item "New Product", new_product_path %>
        <%= menu_item "Departments", departments_path %>
      <% end %>
      <%= form_tag search_product_path, class: "navbar-form navbar-right", method: :get do %>
        <div class = "form-group">
          <%= text_field_tag :name, @name, class: "form-control" %>
          <%= button_to "Seach", nil, class: "btn btn-default" %>
        </div>
      <% end %>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<% @product.errors.full_messages.each do |msg| %>
  <div class = "alert alert-danger" role = "alert">
    <%= msg %>
  </div>
<% end %>
<%= form_for @product do |form| %>
  <div class = "row">
    <div class = "col-sm-8">
      <div class = "form-group">
        <%= form.label :name %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class = "row">
    <div class = "col-sm-8">
      <div class = "form-group">
        <%= form.label :description %>
        <%= form.text_area :description, class: "form-control", rows: 4 %>
      </div>
    </div>
  </div>

  <div class = "row">
    <div class = "col-sm-4">
      <div class = "form-group">
        <%= form.label :department %>
        <%= form.collection_select :department_id, @department, :id, :name, {}, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class = "row">
    <div class = "col-sm-4">
      <div class = "form-group">
        <%= form.label :price %>
        <%= form.number_field :price, class: "form-control", step: "0.01" %>
      </div>
    </div>
    <div class = "col-sm-4">
      <div class = "form-group">
        <%= form.label :stock %>
        <%= form.number_field :stock, class: "form-control" %>
      </div>
    </div>
  </div>

  <%= form.submit action_text, class: "btn btn-primary" %>
  <%= link_to "Back", products_path, class: "btn btn-default" %>
<% end %>

<div>
</div>

app/views/products/_product.html.erb
<tr>
    <td><%= product.name %></td>
    <td><%= product.description %></td>
    <td><%= product.department.name %></td>
    <td><%= product.price %></td>
    <td><%= product.stock %></td>
    <td style = "text-align:center; width: 10%">
        <%= link_to "Edit", edit_product_path(product), class: "btn btn-primary"%>
    </td>
    <td style = "text-align:center; width: 10%">
        <%= button_to "Delete", product, method: :delete, class: "btn btn-danger",
        data: {confirm: "Are you sure you want to remove #{product.name}"} %>
    </td>
</tr>

app/views/products/_product_head.html.erb
<tr>
    <td>Name</td>
    <td>Description</td>
    <td>Department</td>
    <td>Price</td>
    <td>Stock</td>
    <td colspan="2" >
</tr>

app/views/products/edit.html.erb
<%= render "form", action_text: "Save" %>

app/views/products/index.html.erb
<% if flash[:notice] %>
  <div class = "alert alert-info" role = "alert">
    <%= flash[:notice] %>
  </div>
<% end %>
<table class="table table-bordered table-hover">
  <%= render :partial => "products/product_head" %>
  <%= render @products_not_on_sale %>
</table>
<div class = "alert alert-success text-center" role = "alert">
  <h2 class = "alert-heading">On Sale</h2>
</div>
<table class="table table-bordered">
  <%= render "product_head" %>
  <%= render @on_sale %>
</table>

<div>
  <%= link_to "New Product", new_product_path, class: "btn btn-default" %>
</div>

app/views/products/new.html.erb
<%= render "form", action_text: "Create" %>

app/views/products/search.html.erb
<table class="table table-bordered table-hover">
  <%= render "product_head" %>
  <%= render @search %>
</table>